import type { Metadata } from "next";
import { Gowun_Dodum, Nanum_Myeongjo, Song_Myung } from "next/font/google";
import "./globals.css";

const gowunDodum = Gowun_Dodum({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gowun-dodum",
});

const nanumMyeongjo = Nanum_Myeongjo({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-nanum-myeongjo",
});

const songMyung = Song_Myung({
  weight: "400",
  variable: "--font-song-myung",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gowunDodum.variable} ${nanumMyeongjo.variable} ${songMyung.variable} text-lg leading-relaxed tracking-tight antialiased`}
      >
        <div className="w-full h-full shadow-2xl">{children}</div>
      </body>
    </html>
  );
}
