import type { Metadata } from "next";
import { Noto_Serif_KR, Parisienne, Nanum_Pen_Script } from "next/font/google";

import "./globals.css";

const parisienne = Parisienne({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-parisienne",
});

const notoSerif = Noto_Serif_KR({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noto-serif-kr",
});

const nanumPen = Nanum_Pen_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-nanum-pen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif.variable} ${nanumPen.variable} ${parisienne.variable} text-base leading-relaxed tracking-tight antialiased`}
      >
        <div className="w-full h-full shadow-2xl">{children}</div>
      </body>
    </html>
  );
}
